title: pygsutils
author: Gautam Sisodia
exclude_patterns: 
  - README.md
repository:
  url: https://github.com/gautsi/pygsutils
html:
  use_repository_button: true
execute:
  execute_notebooks: auto
sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
  config:
    nb_custom_formats:
        .py:
            - jupytext.reads
            - fmt: py:percent